version: '3'
services:
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./app:/app
      - ./docker/app-entrypoint:/entrypoint
    ports:
      - 8080:8080
    entrypoint: /entrypoint/entrypoint.sh
    command: runserver
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: lines
      POSTGRES_USER: lines
      POSTGRES_DB: lines
    volumes:
      - ./docker/db-entrypoint:/docker-entrypoint-initdb.d
